export default [
    {
        "id": 1,
        "postType": "hobby",
        "post": "I was wondering if there is anyone interested in playing foot ball today after noon",
        "name": "flexy rabbit",
        "location":"Jeonmin-dong,Munji,Daejeon",
        "time":"1hrs ago",
        "like": 1,
        "comment": 4,
        "interested": 1,
        "replies": 12,

    },
    {
        "id": 2,
        "postType": "hobby",
        "post": "I was wondering if there is anyone interested in playing foot ball today after noon",
        "name": "flexy rabbit",
        "location":"Daehak-rog,KAIST,Daejeon",
        "time":"1hrs ago",
        "like": 1,
        "comment": 7,
        "interested": 1,
        "replies": 2,

    },
    {
        "id": 3,
        "postType": "hobby",
        "post": "I was wondering if there is anyone interested in playing foot ball today after noon",
        "name": "flexy rabbit",
        "location":"Jeonmin-dong,Munji,Daejeon",
        "time":"1hrs ago",
        "like": 1,
        "comment": 4,
        "interested": 1,
        "replies": 2,

    },
    {   "id": 4,
        "postType": "Restaurant",
        "post": "I was wondering if there is a good pizza house near by this neighboorhood",
        "name": "amzon rabit",
        "location":"Daehak-rog,KAIST,Daejeon",
        "time":"3hrs ago",
        "like": 1,
        "comment": 7,
        "interested": 1,
        "replies": 2,

    },
    {   "id": 5,
        "postType": "Question",
        "post": "I was wondering if there is anyone interested in playing foot ball today after noon",
        "name": "afromarxos",
        "location":"Jeonmin-dong,Munji,Daejeon",
        "time":"1hrs ago",
        "like": 12,
        "comment": 4,
        "interested": 12,
        "replies": 1,

    },
    {   "id": 6,
        "postType": "Dailylife",
        "post": "I was going to school today and met a kpop singer who waned to find a coffeshop and took a snap with him",
        "name": "flexy rabbit",
        "location":"Daehak-rog,KAIST,Daejeon",
        "time":"1hrs ago",
        "like": 12,
        "comment": 7,
        "interested": 1,
        "replies": 2,

    },
    {   "id": 7,
        "postType": "hobby",
        "post": "I was wondering if there is anyone interested in playing foot ball today after noon",
        "name": "flexy rabbit",
        "location":"Jeonmin-dong,Munji,Daejeon",
        "time":"1hrs ago",
        "like": 1,
        "comment": 4,
        "interested": 1,
        "replies": 2,

    },
    {   "id": 8,
        "postType": "hobby",
        "post": "I was wondering if there is anyone interested in playing foot ball today after noon",
        "name": "flexy rabbit",
        "location":"Daehak-rog,KAIST,Daejeon",
        "time":"1hrs ago",
        "like": 1,
        "comment": 7,
        "interested": 1,
        "replies": 2,

    },
    {   "id": 9,
        "postType": "hobby",
        "post": "I was wondering if there is anyone interested in playing foot ball today after noon",
        "name": "flexy rabbit",
        "location":"Jeonmin-dong,Munji,Daejeon",
        "time":"1hrs ago",
        "like": 1,
        "comment": 4,
        "interested": 1,
        "replies": 2,

    },
    {   "id": 10,
        "postType": "hobby",
        "post": "I was wondering if there is anyone interested in playing foot ball today after noon",
        "name": "flexy rabbit",
        "location":"Daehak-rog,KAIST,Daejeon",
        "time":"1hrs ago",
        "like": 1,
        "comment": 7,
        "interested": 1,
        "replies": 2,

    },
    {   "id": 11,
        "postType": "hobby",
        "post": "I was wondering if there is anyone interested in playing foot ball today after noon",
        "name": "flexy rabbit",
        "location":"Jeonmin-dong,Munji,Daejeon",
        "time":"1hrs ago",
        "like": 1,
        "comment": 4,
        "interested": 1,
        "replies": 2,

    },
    {   "id": 12,
        "postType": "hobby",
        "post": "I was wondering if there is anyone interested in playing foot ball today after noon",
        "name": "flexy rabbit",
        "location":"Daehak-rog,KAIST,Daejeon",
        "time":"1hrs ago",
        "like": 1,
        "comment": 7,
        "interested": 1,
        "replies": 2,

    },
    {   "id": 13,
        "postType": "hobby",
        "post": "I was wondering if there is anyone interested in playing foot ball today after noon",
        "name": "flexy rabbit",
        "location":"Jeonmin-dong,Munji,Daejeon",
        "time":"1hrs ago",
        "like": 1,
        "comment": 4,
        "interested": 1,
        "replies": 2,

    },
    {   "id": 14,
        "postType": "hobby",
        "post": "I was wondering if there is anyone interested in playing foot ball today after noon",
        "name": "flexy rabbit",
        "location":"Daehak-rog,KAIST,Daejeon",
        "time":"1hrs ago",
        "like": 1,
        "comment": 7,
        "interested": 1,
        "replies": 2,

    },
    {   "id": 15,
        "postType": "hobby",
        "post": "I was wondering if there is anyone interested in playing foot ball today after noon",
        "name": "flexy rabbit",
        "location":"Jeonmin-dong,Munji,Daejeon",
        "time":"1hrs ago",
        "like": 1,
        "comment": 4,
        "interested": 1,
        "replies": 2,

    },
    {   "id": 16,
        "postType": "hobby",
        "post": "I was wondering if there is anyone interested in playing foot ball today after noon",
        "name": "flexy rabbit",
        "location":"Daehak-rog,KAIST,Daejeon",
        "time":"1hrs ago",
        "like": 1,
        "comment": 7,
        "interested": 1,
        "replies": 2,

    }
]